SameWave/action-chat-client

- README.md
- ember-cordova/cordova/config.xml
https://www.pivotaltracker.com/story/show/129918145
> Add android platform to project

- app/chat-box/component.js
- app/chat-box/template.hbs
- app/components/auto-resize-textarea/component.js
- app/stream/template.hbs
- app/styles/abstracts/_settings.scss
- app/styles/abstracts/_utilities.scss
- app/styles/app.scss
- app/styles/base/_reset.scss
- app/styles/components/_auto-resize-textarea.scss
- app/styles/components/_chat-box.scss
- tests/integration/components/auto-resize-textarea/component-test.js
https://www.pivotaltracker.com/story/show/129930441
> Resizable textarea

- app/stream/index/template.hbs
- app/styles/abstracts/_settings.scss
- app/styles/components/_tabs.scss
https://www.pivotaltracker.com/story/show/130172933
> Add transition and icon to tabs

- app/chat-box/template.hbs
- app/comments-section/component.js
- app/components/auto-resize-textarea/component.js
- app/login/template.hbs
- app/stream/index/chat/controller.js
- app/stream/index/chat/template.hbs
- app/stream/index/route.js
- app/stream/index/scoreboard/template.hbs
- app/stream/index/template.hbs
- app/streams/template.hbs
- app/styles/_general.scss
- app/styles/abstracts/_settings.scss
- app/styles/app.scss
- app/styles/components/_chat-box.scss
- app/styles/components/_comments-section.scss
- app/styles/components/_footer.scss
- app/styles/components/_tabs.scss
- app/styles/layout/_body.scss
- app/styles/layout/_footer.scss
- app/transitions.js
https://www.pivotaltracker.com/story/show/130345713
> Footer fixes

- README.md
- app/chat-box/component.js
- app/components/auto-resize-textarea/component.js
https://www.pivotaltracker.com/story/show/130430625
> Chat box area reset height

- app/comments-section/template.hbs
- app/components/message-marker/component.js
- app/styles/_general.scss
- app/styles/abstracts/_settings.scss
- app/styles/app.scss
- app/styles/components/_message-marker.scss
Style new messages marker UI Element.
> New message marker

- app/comments-section/template.hbs
- app/stream/index/chat/template.hbs
- app/styles/abstracts/_animations.scss
- app/styles/abstracts/_settings.scss
- app/styles/app.scss
- app/styles/components/_buttons.scss
- app/styles/components/_load-earlier.scss
- app/styles/components/_loading-page.scss
https://www.pivotaltracker.com/story/show/130430645
load earlier now has a loading state
> style load earlier button

- .eslintrc.js
- app/application/adapter.js
- app/application/controller.js
- app/authenticators/jwt.js
- app/authorizers/custom.js
- app/comment/adapter.js
- app/comment/model.js
- app/components/comments-section/component.js
- app/components/stream-comment/component.js
- app/helpers/date-format.js
- app/login/controller.js
- app/member/model.js
- app/person/model.js
- app/session/service.js
- app/stream/index/chat/controller.js
- app/stream/index/chat/route.js
- app/stream/index/scoreboard/controller.js
- app/stream/index/scoreboard/route.js
- app/streams/controller.js
I've left the id properties alone the rest is sorted.
> Eslint fixes

- app/styles/components/_comments-section.scss
https://www.pivotaltracker.com/story/show/130509583
> Let user close keyboard on stream chat when tapping on empty section

- app/styles/components/_header.scss
https://www.pivotaltracker.com/story/show/130510579
> Changed header layout increase hit areas

- app/styles/base/_reset.scss
- app/styles/components/_comments-section.scss
- app/styles/components/_stream-comment.scss
- package.json
https://www.pivotaltracker.com/story/show/130172925
> Comment section bounce

- app/styles/components/_stream-comment.scss
https://www.pivotaltracker.com/story/show/130616921
> wrap comments and auto hyphenate

- README.md
- ember-cordova/cordova/config.xml
https://www.pivotaltracker.com/story/show/130616919
> Bump up cordova wkwebview plugin version

- app/components/chat-box/template.hbs
- app/styles/base/_reset.scss
- app/styles/components/_chat-box.scss
- app/styles/components/_footer.scss
- app/styles/components/_tabs.scss
https://www.pivotaltracker.com/story/show/130616925
> Tab menu height

- app/styles/components/_chat-box.scss
- app/styles/components/_footer.scss
- app/styles/components/_keyboard-push.scss
> visual styling fixes for chat box

- app/components/chat-box/component.js
- app/components/chat-box/template.hbs
- app/stream/index/chat/controller.js
- app/stream/index/chat/template.hbs
> Missing cursor fix

- app/components/message-marker/template.hbs
- app/styles/components/_message-marker.scss
https://www.pivotaltracker.com/story/show/131146267
> Style message marker fade out

- .stylelintrc
- README.md
- app/components/stream-comment/template.hbs
- app/freestyle/template.hbs
- app/streams/controller.js
- app/streams/template.hbs
- app/styles/_general.scss
- app/styles/abstracts/_utilities.scss
- app/styles/components/_media-block.scss
- app/styles/components/_stream-message.scss
- package.json
Adds linting for css and remove ember-hammertime as it is the source of allot of issues.
> Install stylelint

- app/styles/layout/_body.scss
https://www.pivotaltracker.com/story/show/131485277
> Add overscroll to stream scoreboard

- app/components/chat-box/component.js
- app/components/chat-box/template.hbs
- app/stream/index/chat/controller.js
- app/stream/index/chat/template.hbs
- app/styles/abstracts/_animations.scss
- app/styles/components/_chat-box.scss
https://www.pivotaltracker.com/story/show/131520667
> Chat box send button visibility

- ember-cordova/cordova/config.xml
https://www.pivotaltracker.com/story/show/130616919
> Bump up wkwebview to fix emojis

- app/components/comments-section/component.js
- app/components/streams-section/component.js
- app/mixins/swipable-list.js
https://www.pivotaltracker.com/story/show/131278259
> @Graeme simple implementation

- app/stream/index/chat/route.js
https://www.pivotaltracker.com/story/show/131485301
> Allows non-member (admin) to view a chat without triggering errors

- app/styles/components/_chat-box.scss
https://www.pivotaltracker.com/story/show/131872109
> Fix animation of send button

- app/components/goal-block/component.js
- app/components/goal-block/template.hbs
- app/stream/index/scoreboard/controller.js
- app/stream/index/scoreboard/template.hbs
https://www.pivotaltracker.com/story/show/131877523
> Add isEditing conditional to goal blocks

- app/components/goal-block/component.js
- app/mixins/swipable-list-item.js
- app/styles/components/_media-block.scss
https://www.pivotaltracker.com/story/show/132154327
> One option block

- app/components/goal-block/component.js
- app/components/goal-block/template.hbs
- app/components/tool-bar/component.js
- app/components/tool-bar/template.hbs
- app/mixins/swipable-list-item.js
- app/styles/abstracts/_settings.scss
- app/styles/components/_media-block.scss
- app/styles/components/_option-block.scss
- app/styles/components/_tool-bar.scss
https://www.pivotaltracker.com/story/show/131877527
> Goal block options

- app/components/stream-comment/component.js
- app/styles/components/_stream-comment.scss
https://www.pivotaltracker.com/story/show/132138971
> Swipe close comment block on edit

- app/stream/index/chat/controller.js
https://www.pivotaltracker.com/story/show/131871687
> Resize stream comment after edit
